### ISSUE TITLE
Support and settings for multiple feeds

### ISSUE THREAD

**Issue by mirkobrombin** [Allen-B1/news#10]
Will be possible to add and manage RSS feeds?

**Comment by Allen-B1** [comment]
Maybe

**Comment by Allen-B1** [comment]
Well, I'll add that to the todo. Thanks for suggesting!

**Comment by Allen-B1** [comment]
I'm working on it: https://github.com/Allen-B1/news/commit/a16be695e6527b5b45fb46a57283a8e2c888d293
