### ISSUE TITLE
News reference from commit 1d69dbf

### ISSUE THREAD

**Issue by mirkobrombin** [Allen-B1/news#12]
From commit 1d69dbf you reference to "News":
`..
News.add_page(null);
..`
which is not declared and return errors on build:

`news.vala:105.21-105.24: error: The name `News' does not exist in the context of `main'
    root.pack_start(News.create_toolbar(window), false, false, 0);
                    ^^^^
news.vala:111.5-111.8: error: The name `News' does not exist in the context of `main'
    News.add_page(null);
    ^^^^
Compilation failed: 2 error(s), 0 warning(s)
`

**Comment by Allen-B1** [comment]
ok

**Comment by Allen-B1** [comment]
Have you run
```bash
cmake /usr ./
```
again and not just `make`? Try that

**Comment by mirkobrombin** [comment]
Yes

**Comment by Allen-B1** [comment]
It works now (at least for me). Maybe you're not on the newest version? (`git pull`)

**Comment by Allen-B1** [comment]
I forgot to add `widgets.vala` oops. Does it work now?

**Comment by mirkobrombin** [comment]
I think yes. Previously I had to use wake for the build because of a problem with "cmake /usr ./"
`CMake Error at CMakeLists.txt:24 (find_package):
  By not providing "FindVala.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Vala", but
  CMake did not find one.

  Could not find a package configuration file provided by "Vala" with any of
  the following names:

    ValaConfig.cmake
    vala-config.cmake

  Add the installation prefix of "Vala" to CMAKE_PREFIX_PATH or set
  "Vala_DIR" to a directory containing one of the above files.  If "Vala"
  provides a separate development package or SDK, be sure it has been
  installed.
`

**Comment by Allen-B1** [comment]
Ok so it works now right?

**Comment by mirkobrombin** [comment]
can't build see my latest comment 😂

**Comment by Allen-B1** [comment]
Oh that! Are you on Elementary OS? If so, try

```bash
sudo apt install elementary-sdk
```

**Comment by mirkobrombin** [comment]
yes Loki 0.4.1

**Comment by Allen-B1** [comment]
Did installing the `elementary-sdk` work?

**Comment by mirkobrombin** [comment]
I will try after dinner

**Comment by Allen-B1** [comment]
Ok, when you try, if it works, close this issue. Thanks for reporting this to me!

**Comment by mirkobrombin** [comment]
It's working!
