### ISSUE TITLE
Using HeaderBar instead Toolbar

### ISSUE THREAD

**Issue by mirkobrombin** [Allen-B1/news#13]
It might be a good idea to use a Headerbar instead of the window frame plus a Toolbar. It would save space as well as better integrate the application with system design.

[ElementaryOS Human Interface Guidelines](https://elementary.io/it/docs/human-interface-guidelines#appmenu) says "You should first consider if your app needs this widget. While most apps may have one, your app may not necessarily need an AppMenu." I think this is the one.

HeaderBar is documented [here](https://valadoc.org/gtk+-3.0/Gtk.HeaderBar.html) and [here](https://github.com/robertsanseries/template-for-vala-apps) a good example. :D 

![senzanome](https://user-images.githubusercontent.com/9479903/30524860-c5be2b84-9bfb-11e7-9e3e-81c6ccc7d95b.png)

**Comment by Allen-B1** [comment]
Oh thanks! I've always wondered how they do that

**Comment by Allen-B1** [comment]
Fixed
