### ISSUE TITLE
Can't add source

### ISSUE THREAD

**Issue by greo-d** [Allen-B1/news#16]
I installed **News 1.0.4** from Appcenter few minutes ago but i can't add any source manually.
I'm able to select the text-field but can't add any text inside. 
![bildschirmfoto von 2017-09-18 18 56 52](https://user-images.githubusercontent.com/23266409/30554107-b1f16032-9ca3-11e7-81fc-616f1069e5eb.png)

**Comment by Allen-B1** [comment]
Oh! Thanks for reporting this bug. I'll get it fixed as soon as I can.

**Comment by Allen-B1** [comment]
Hmm... that's weird

**Comment by Allen-B1** [comment]
Fixed! https://github.com/Allen-B1/news/commit/2b613f025c1141e5a46f2d46951a07ce1fb93db5

**Comment by Allen-B1** [comment]
It'll be released in 1.0.6
