### ISSUE TITLE
In-app reader

### ISSUE THREAD

**Issue by mirkobrombin** [Allen-B1/news#17]
It may be practical to extract the news from the RSS feed and read it directly into the application.

**Comment by Allen-B1** [comment]
Yeah, that sounds like a good idea

**Comment by Allen-B1** [comment]
So you mean display the html? Or display the link contents

**Comment by mirkobrombin** [comment]
The formatted text (HTML)

**Comment by Allen-B1** [comment]
For the description?

**Comment by mirkobrombin** [comment]
No for the content. The idea is to show the text of the news once clicked on the title instead of opening the link in the browser.

**Comment by Allen-B1** [comment]
Ok, so like a WebView

**Comment by mirkobrombin** [comment]
Yes! Just do not show the site. It would be great to extract only HTML text in order to facilitate reading.

**Comment by Allen-B1** [comment]
Ok, but how would we do that?

**Comment by mirkobrombin** [comment]
As Google News restricts information in RSS feeds, we should limit this feature to the RSS feeds that have been added manually.
All RSS feeds contain 3 basic tags (title, link, content:encoded), for example, the RSS feed of my website: https://linuxhub.it/feed have the tag <content:encoded> that contains encoded text.
We can pick up that content and show it at the click of the single news, to a new tab in the DynamicNotebook.

**Comment by Allen-B1** [comment]
Oh, now I get it. Not all feeds have `<content:encoded>` though (like [CNN](http://rss.cnn.com/rss/cnn_world.rss)). I'm thinking of using an actual xml/rss parser, instead of just parsing the site (like this https://developer.gnome.org/glib/stable/glib-Simple-XML-Subset-Parser.html)

**Comment by Allen-B1** [comment]
Thanks for the (wonderful) suggestion!

**Comment by Allen-B1** [comment]
I'm using `libxml2` to parse the xml and I'll add that feature soon

**Comment by mirkobrombin** [comment]
Nice!

**Comment by Allen-B1** [comment]
But what if there isn't a `<content:encoded>` tag? Should it just open a new WebView tab?

**Comment by mirkobrombin** [comment]
I think yes. This tag may be a standard, if not just open the webpage :relaxed:

**Comment by mirkobrombin** [comment]
I think yes. This tag may be a standard, if not just open the webpage :relaxed:

**Comment by robertsanseries** [comment]
@Allen-B1 

I believe that the code of this application can help you:

https://github.com/jangernert/FeedReader 

Note: Although the developer created the elemental thinking, he decided not to take to the AppCenter of the OS elementary! (Issue: https://github.com/jangernert/FeedReader/issues/494)

I believe this design is what @mirkobrombin was talking about.

![1screenshot2](https://user-images.githubusercontent.com/11967501/30774993-6e5e813a-a061-11e7-8d81-3e95a39a8f25.png)


<strike>it would be interesting if your app had a similar design!</strike>

**Comment by mirkobrombin** [comment]
Yeah! That's what I mean, without the sidebar to the left

**Comment by Allen-B1** [comment]
Ok! I'm assuming the widget on the right is a `WebView` right?

**Comment by robertsanseries** [comment]
Yes!

**Comment by Allen-B1** [comment]
Ok. But from my experience, I'd had trouble making the WebView the size of the container

**Comment by Allen-B1** [comment]
Wait, its working!

**Comment by Allen-B1** [comment]
Try building it

**Comment by mirkobrombin** [comment]
Yeah!
![schermata da 2017-09-24 16-30-57](https://user-images.githubusercontent.com/9479903/30783594-cc115d54-a145-11e7-8ade-6ae33955c9e0.png)

Just a few observations:
- the description of the left column should show a small number of characters (250?)
- The overall window size should be at least 1100px wide
- To the right, only the title and text of the <content> article should be displayed to make it easier to read. The web version would only show it if an RSS feed does not have the <content> tag

**Comment by Allen-B1** [comment]
@mirkobromin Thanks, but:

1. The user can resize the window, and if they're display is too small, it's going to be a problem if the window is too big
2. The description on the left should not show html markup, if it didn't, it would probably have a smaller number of characters, but unfortunately the Pango Markup Language doesn't support `<a>` & other tags so there's an error... (it just shows in text if it doesn't work) https://developer.gnome.org/pango/stable/PangoMarkupFormat.html
I'm currently working on that

**Comment by mirkobrombin** [comment]
Ok :grinning:

**Comment by Allen-B1** [comment]
See #22
