### ISSUE TITLE
Granite library

### ISSUE THREAD

**Issue by mirkobrombin** [Allen-B1/news#18]
The Granite library offers a large number of advanced widget features, it might be a good idea to take advantage of it.
Many of them might be useful:
- SimpleSettingsPage (offer a section where the user can set various settings such as whether to save the current session)
- Welcome (a start page for the user who shows basic functionality such as Google News or adds a custom rss feed)
- DynamicNotebook (They offer various standard features such as the close button)

[Here](https://github.com/elementary/granite/tree/master/demo/Views) you can find an example with a demo application and [here](https://elementary.io/docs/human-interface-guidelines#human-interface-guidelines) some components are explained.

I know I'm turning to your worst nightmare 😂

**Comment by Allen-B1** [comment]
Great idea! Now I can actually add the close button without coding it myself :)

**Comment by mirkobrombin** [comment]
Happy to help you

**Comment by Allen-B1** [comment]
When I try to compile, it returns this error:
```
/home/.../.../news.c: fatal error: granite.h: No such file or directory
compilation terminated.
```

**Comment by mirkobrombin** [comment]
Is granite installed?

**Comment by Allen-B1** [comment]
Yep, I installed `libgranite-dev`

**Comment by Allen-B1** [comment]
When I compile directly with `valac` it works, but when I use `cmake` it doesn't.

**Comment by mirkobrombin** [comment]
Mmh try to open an issue on the github page

**Comment by mirkobrombin** [comment]
Mmh try to open an issue on the github page

**Comment by Allen-B1** [comment]
Ok

**Comment by mirkobrombin** [comment]
If you open an issue link to this please

**Comment by Allen-B1** [comment]
Do you think we could get away with using `make` directly? This project https://github.com/lainsce/notejot doesn't use `cmake`

**Comment by mirkobrombin** [comment]
I think yes

**Comment by Allen-B1** [comment]
Ok, I'll do that

**Comment by Allen-B1** [comment]
I changed `Gtk.Notebook` to `Granite.Widgets.DynamicNotebook`
