### ISSUE TITLE
Headerbar color

### ISSUE THREAD

**Issue by mirkobrombin** [Allen-B1/news#20]
Like other Elementary apps (cyano, eddy,..), may be a good idea to add a background color to the headerbar.

**Comment by Allen-B1** [comment]
Lots of apps don't have headerbar colors though

**Comment by mirkobrombin** [comment]
I know

**Comment by Allen-B1** [comment]
I don't see any reason *to* put a headerbar color

**Comment by mirkobrombin** [comment]
Just a brand identification

**Comment by Allen-B1** [comment]
Thanks for the suggestion! I'll consider it

**Comment by Allen-B1** [comment]
How do you do it?

**Comment by mirkobrombin** [comment]
I made an example in youplay pull request
https://github.com/Allen-B1/youplay/pull/5/commits/4ce222eb959d59f71e96a752dbd1226c113470a0

**Comment by Allen-B1** [comment]
Ok, did it :)
