### ISSUE TITLE
Added sources don't stay after restart.

### ISSUE THREAD

**Issue by JonnyCodewalker** [Allen-B1/news#23]
Any sources added disappear after closing and reopening the App, leaving only Google News to stay.
Hackernews is also affected by that.

**Comment by mirkobrombin** [comment]
There is currently no database and session save.

**Comment by JonnyCodewalker** [comment]
Is there any ETA on when we can expect that to change?

**Comment by Allen-B1** [comment]
As soon as I get the thing to build
