### ISSUE TITLE
trouble with koi8-r encoding

### ISSUE THREAD

**Issue by xevin** [Allen-B1/news#45]
what i do:
1. add http://www.opennet.ru/opennews/opennews_all.rss
2. "??????" in tab title and empty titles in news 
![2017-11-04 12-08-25](https://user-images.githubusercontent.com/5955821/32403341-2596435c-c159-11e7-817a-69572e888bb0.png)

**Comment by Allen-B1** [comment]
It works in v1.2.2

![Screenshot](https://user-images.githubusercontent.com/28495335/42125940-e4c53cc4-7c4d-11e8-858d-d7a19c1c3853.png)
