### ISSUE TITLE
Provide an integration point for other apps to use

### ISSUE THREAD

**Issue by alcinnz** [Allen-B1/news#50]
I'm developing a browser and would like to be able to prompt websurfers to add a webfeed to an external feedreader like News. This would greatly improve the experience of apps like yours.

Ideally we'd define a standard between us, Vocal, and anyone else who might be interested so our apps can be loosely coupled.

P.S. While I don't know CMake very well, I will offer to help you switch over to Meson and get that building on houston.

**Comment by alcinnz** [comment]
By the way, I like the screenshots present on the AppCenter and would love to have that version installed.

**Comment by alcinnz** [comment]
Looked into things a little, and I'm sad to say that the failure points are not obvious enough that I can just confidently fix your problem.

Your build files seems to work on my machine, so without engaging with you or the Houston service to figure out what's wrong I can't know if I've fixed your problem. I'll look more into what Houston reported on this issue tracker but those can be hard to interpret.

---

Pity, I would have liked an actively developed feed reader to be present on the AppCenter. And I've got my hands full with Odysseus.

I think I'll close this, as you've got bigger problems to worry about.

**Comment by Allen-B1** [comment]
@alcinnz I think there's already a standard? (service?) for that - https://github.com/elementary/contractor

**Comment by alcinnz** [comment]
Yes there's general purpose standards for this, particularly elementary's Contractor and FreeDesktop.Org's MIME-Apps. But I think feedreaders like your's will benefit from web browsers like mine being able to integrate deeper than what those standards allow.

So I drafted an extension for the FreeDesktop.Org standards at https://github.com/alcinnz/rrs/blob/master/rrs.md that's specific to the domain of feedreaders.

**Comment by alcinnz** [comment]
So can I at least ask you to register support for opening "application/rss+xml" and "application/atom+xml" URLs? That's the least I'm planning to require in order to integrate with apps like yours.
