### ISSUE TITLE
Option for tabs to be on the side

### ISSUE THREAD

**Issue by BNolet** [Allen-B1/news#72]
I'd like to be able to see the tabs on the side rather than the top

**Comment by Allen-B1** [comment]
I'm thinking of making this the default because most aggregators use this design; it would be more familiar to new users.

It's also more flexible: It would be possible to put sources under categories (#73) while implementing it using the current tabbed design would be hard.

**Comment by BNolet** [comment]
Oh wow, yeah absolutely see where you're coming from! Well I'm glad that my issue followed the natural evolution of the project

**Comment by Allen-B1** [comment]
I've already implemented the changes; it'll be coming in the next release.
