### ISSUE TITLE
RSS / Atom Feed Autodiscovery

### ISSUE THREAD

**Issue by Allen-B1** [Allen-B1/news#77]
TL;DR: Any of these three
1. `<link rel="alternate" type="application/rss+xml" href="...">`
2. `<link rel="alternate" type="application/atom+xml" href="...">`
3. `<link rel="feed" href="...">`

Also note that the `rel` attribute can have more than one keyword (i.e. `alternate feed` or `canonical feed` etc.).

`alternate stylesheet` can not be a feed.

If there are multiple, choose first `<link>` element.

http://www.rssboard.org/rss-autodiscovery
https://blog.whatwg.org/feed-autodiscovery

**Comment by alcinnz** [comment]
I've already implemented this for my web browser and am in the process of releasing that update.

I'll be more than happy to help you integrate into that so people don't need to copy and paste links into News. It'll be very trivial.

**Comment by alcinnz** [comment]
Nevermind, you've done all that's necessary already. Odysseus will automatically start advertising News as soon as both of our updates are out!
