### ISSUE TITLE
ID in appdata.xml doesn't match project RDNN

### ISSUE THREAD

**Issue by danirabbit** [Allen-B1/news#8]
https://github.com/Allen-B1/news/blob/8fa7d20255e536dc98c9d220f01f52e100df25e5/data/com.github.allen-b1.news.appdata.xml#L4

This should be your RDNN (`com.github.allen-b1.news`)

**Comment by Allen-B1** [comment]
https://github.com/Allen-B1/news/commit/789647c353acf6cae7f3bf59bc4c54e02573dd5a
