### ISSUE TITLE
Change required for AppCenter: OARS Social Info value

### ISSUE THREAD

**Issue by cassidyjames** [Allen-B1/news#85]
Thanks for submitting your latest release to AppCenter! However, while reviewing the submission, we found an issue that needs to be resolved.

Since your app uses an external web service, its `social-info` value **must** be set to `mild` or higher, depending on the data that is sent. You can always ensure your OARS data is correct by using the [official OARS generator](https://hughsie.github.io/oars/).

https://github.com/Allen-B1/news/blob/eccb01b5ff11ef92daee8ec344bc92d25b21a18d/data/com.github.allen-b1.news.appdata.xml.in#L85

Once you've made the requested changes, create a new release on GitHub and re-submit it to the [AppCenter Dashboard](https://developer.elementary.io). As always, if you have any questions you can reply here.

**Comment by Allen-B1** [comment]
Thanks for the information!

**Comment by cassidyjames** [comment]
Thanks for the quick turnaround! Your latest release has been accepted. :)
