### ISSUE TITLE
You must provide a unique icon

### ISSUE THREAD

**Issue by danirabbit** [Allen-B1/news#9]
https://github.com/Allen-B1/news/blob/8fa7d20255e536dc98c9d220f01f52e100df25e5/data/com.github.allen-b1.news.desktop#L7

You cannot use system icons to represent your application. You must provide a unique icon named with your RDNN

**Comment by Allen-B1** [comment]
Oops wrong issue

**Comment by mirkobrombin** [comment]
I'm not a designer, but my draft might be a start point 😋 ([SVG](http://svgur.com/i/32C.svg))
![news-icon](https://user-images.githubusercontent.com/9479903/30525037-23e99cb8-9bff-11e7-9538-4e6eafe8bb06.png)

**Comment by Allen-B1** [comment]
That looks pretty good

**Comment by mirkobrombin** [comment]
So let me know what format and size you need!

**Comment by Allen-B1** [comment]
I think we need svg: go to `/usr/share/icons/hicolor/128x128/apps/` in your files

**Comment by Allen-B1** [comment]
Done
